package com.gupaoedu.designpattern.factory.bean;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AirConditioner.java
//  @ Date : 2019/3/19/�ܶ�
//  @ Author : vier
//
//


public interface AirConditioner {
    void coolCown();
}
