package com.gupaoedu.designpattern.factory.bean;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HairFrige.java
//  @ Date : 2019/3/19/�ܶ�
//  @ Author : vier
//
//




public class HairFrige implements Ifrige {
	public void refrigerate(){
        System.out.println(" 海尔冰箱，质量所在!");
    }
}
